apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: churn-dev
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: churn-api
- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 2
  target:
    kind: HorizontalPodAutoscaler
    name: churn-api
images:
- name: churn-api
  newName: ghcr.io/boderux/churn-api
  newTag: sha-1ab24dc4
